version: '3'

services:
  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" 
        --reload
        "block_chain.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/block_chain'
    ports:
      - '8000:8000'

#
# > is treated as following lines are treated as a paragraph  blank line separates paragraphs
# 
#

# 
# gunicorn command
#from http://docs.gunicorn.org/en/latest/run.html
#gunicorn [OPTIONS] APP_MODULE
#  application.app:create_app()  is app module
# -c is configuration file
# python:  specifies a python module
#